basePath: /api/v1
definitions:
  http.CreateMessageRequest:
    properties:
      content:
        maxLength: 1000
        minLength: 1
        type: string
    required:
    - content
    type: object
  http.UpdateMessageRequest:
    properties:
      content:
        maxLength: 1000
        minLength: 1
        type: string
    required:
    - content
    type: object
  models.Message:
    properties:
      content:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: This is a RESTful API for managing messages
  title: Message Service API
  version: "1.0"
paths:
  /api/v1/messages:
    get:
      description: Get a list of all messages
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Message'
            type: array
      summary: List all messages
      tags:
      - messages
    post:
      consumes:
      - application/json
      description: Create a new message with the provided content
      parameters:
      - description: Message content
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/http.CreateMessageRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Message'
      summary: Create a new message
      tags:
      - messages
  /api/v1/messages/{id}:
    delete:
      description: Delete a message by its ID
      parameters:
      - description: Message ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete a message
      tags:
      - messages
    get:
      description: Get a message by its unique identifier
      parameters:
      - description: Message ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Message'
      summary: Get a message by ID
      tags:
      - messages
    put:
      consumes:
      - application/json
      description: Update a message's content by its ID
      parameters:
      - description: Message ID
        in: path
        name: id
        required: true
        type: string
      - description: Updated message content
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/http.UpdateMessageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Message'
      summary: Update a message
      tags:
      - messages
swagger: "2.0"
